services:
  # Rick and Morty API Backend
  - type: web
    name: rickandmorty-api
    runtime: node
    rootDirectory: apps/api
    buildCommand: npm install -g pnpm && pnpm install && npx prisma generate
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false  # You'll add this manually from Neon
    plan: free
    autoDeploy: true
    branch: main

# Notes:
# 1. Render automatically injects PORT environment variable (no need to set it)
# 2. Free tier: 750 hours/month, spins down after 15 minutes of inactivity
# 3. DATABASE_URL must be added manually in Render dashboard from your Neon database
# 4. Change 'branch: main' to 'branch: development' if deploying from development branch
# 5. Health check uses /graphql endpoint to verify Apollo Server is running
