'use client';

import React from 'react';
import { Button } from '../button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../card';
import { DonationCounter } from '../donation-counter';
import { KofiButton } from '../kofi-button';
import { DONATION_CONFIG } from '@rickandmorty/config/donation';

interface DonationPageProps {
  // Props for the donation page component
}

export const DonationPageContent: React.FC<DonationPageProps> = () => {
  const handleDonation = () => {
    // For now, just show an alert explaining the donation purpose
    alert('This is a placeholder for the donation system. In a real implementation, this would link to a payment processor that only accepts donations for hosting and domain expenses.');
  };

  return (
    <div className="container mx-auto py-8 px-4">
      <Card className="max-w-3xl mx-auto">
        <CardHeader>
          <CardTitle>Support Our Hosting Costs</CardTitle>
          <CardDescription>
            Help keep the Rick and Morty Fan Site running
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-6">
            <DonationCounter targetAmount={75} currentAmount={15} />
            
            <section>
              <h3 className="text-xl font-semibold mb-2">About Our Donation System</h3>
              <p className="mb-4">
                This is a non-profit fan site created to celebrate the Rick and Morty universe. 
                All donations received go directly toward covering hosting and domain expenses 
                to keep this resource available to the community.
              </p>
              <p className="mb-4">
                This project is maintained to remain compatible with Spanish unemployment benefits 
                (prestación contributiva de desempleo) regulations. We do not profit from this site.
              </p>
            </section>

            <section>
              <h3 className="text-xl font-semibold mb-2">Current Expenses</h3>
              <ul className="list-disc pl-5 mb-4">
                <li>Monthly hosting costs: €5</li>
                <li>Domain registration: €15/year</li>
                <li>SSL certificates: €0 (using free certificates)</li>
              </ul>
              <p className="mb-4">
                <strong>Total monthly cost: €6.25</strong> (€5 hosting + €1.25 for domain/year)
              </p>
            </section>

            <section>
              <h3 className="text-xl font-semibold mb-2">Donate to Cover Expenses</h3>
              <p className="mb-4">
                Your donation helps keep this fan site running. All funds go directly toward 
                hosting and domain expenses.
              </p>
              <div className="mb-6">
                <KofiButton />
              </div>
              <p className="text-sm text-gray-600 mb-4">
                (Note: During the autónomo period, donations are temporarily accepted. 
                After the autónomo period ends, this functionality may be disabled 
                to maintain compliance with unemployment benefit regulations.)
              </p>
            </section>

            <section>
              <h3 className="text-xl font-semibold mb-2">Financial Transparency</h3>
              <p className="mb-4">
                As required for compatibility with Spanish unemployment benefits, we maintain 
                complete financial transparency. All donations are used exclusively for hosting 
                and domain expenses. No personal profit is made from this project.
              </p>
              
              <h4 className="font-medium mb-2">Anti-Habitual Income Measures</h4>
              <ul className="list-disc pl-5 mb-4 text-sm">
                <li>No recurring subscriptions or automatic payments</li>
                <li>Donations are completely voluntary with no schedule</li>
                <li>Donation limits: maximum €50/month per person</li>
                <li>No premium features or benefits based on donations</li>
                <li>All content remains free and accessible regardless of donation status</li>
              </ul>
              
              <h4 className="font-medium mb-2">No Profit Motive (No Ánimo de Lucro)</h4>
              <ul className="list-disc pl-5 mb-4 text-sm">
                <li>All donations fund only operational expenses</li>
                <li>The site operates exclusively as a fan resource</li>
                <li>No commercial services or products are offered</li>
                <li>The project remains open source and community-focused</li>
                <li>No personal profit is generated by site operators</li>
              </ul>
            </section>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};